name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses : shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validate composer.json and composer.lock
        run: php composer validate

      - name: Install dependencies
        run: php composer install --prefer-dist --no-progress

      - name: Run phpstan
        run: php vendor/bin/phpstan analyse

      - name: Run phpcs
        run: php vendor/bin/phpcs

      - name: Run phpunit
        run: php ./vendor/bin/phpunit