name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: docker-compose run --rm php composer validate

      - name: Install dependencies
        run: docker-compose run --rm php composer install --prefer-dist --no-progress

      - name: Run phpstan
        run: docker-compose run --rm php vendor/bin/phpstan analyse

      - name: Run phpcs
        run: docker-compose run --rm php vendor/bin/phpcs

      - name: Run phpunit
        run: docker-compose run --rm php ./vendor/bin/phpunit